### ISSUE TITLE
Failed to get UID: -794725232

### ISSUE THREAD

**Issue by megbot3** [HiddenRamblings/Thenaya#10]
First time installing and trying to use with NFC215. Wireless is working and 3DS is updated to newest software. It's the first gen 3DS model.

**Comment by Dimensional** [comment]
As in the Original 3DS that doesn't have NFC at all?

**Comment by urherenow** [comment]
Ahem... https://en-americas-support.nintendo.com/app/answers/detail/a_id/15217/~/how-to-set-up-the-nintendo-3ds-nfc-reader%2Fwriter

**Comment by Dimensional** [comment]
> 
> 
> _cough, cough_ https://en-americas-support.nintendo.com/app/answers/detail/a_id/15217/~/how-to-set-up-the-nintendo-3ds-nfc-reader%2Fwriter

I meant built into the system. Unless I'm mistaken, not having it affect the homebrew.

**Comment by urherenow** [comment]
iirc, when the wireless module is connected, apps/games can’t tell the difference. The 3ds reports that it has nfc, and all commands are the same. (In theory... I tried long ago and had no issue with it working).


Sent from Yahoo Mail for iPhone


On Sunday, May 3, 2020, 10:56, Dimensional <notifications@github.com> wrote:





cough, cough https://en-americas-support.nintendo.com/app/answers/detail/a_id/15217/~/how-to-set-up-the-nintendo-3ds-nfc-reader%2Fwriter


I meant built into the system. Unless I'm mistaken, not having it affect the homebrew.

**Comment by Muchieman7** [comment]
the only way I can replicate this is with an ntag216

**Comment by AbandonedCart** [comment]
Closing this as obsolete. Please resubmit if it is still an issue with the rebuild.
