### ISSUE TITLE
(null) EMPTY DIR

### ISSUE THREAD

**Issue by friskeres** [HiddenRamblings/Thenaya#12]
I wiped my MicroSD a bit ago and upon re-installing Thenaya and trying to browse for amiibo .bin tags, it shows a simple:
![image](https://user-images.githubusercontent.com/23466756/85518851-8d25e380-b5b5-11ea-8f5c-6ce70055d28d.png)
(null)
EMPTY DIR

I'm completely unsure what this is caused by. It worked flawlessly before.

And, with this error, attempting to press B, d-pad right, or R will result in the following crash:
![image](https://user-images.githubusercontent.com/23466756/85518967-ad55a280-b5b5-11ea-8c36-cf0972e29ba9.png)

I installed CFW using the 3ds.hacks.guide instructions. No redirections or anything of the sort.

I know this hasn't been updated in nigh on 3 years, but god damnit I need my amiibos!

**Comment by AbandonedCart** [comment]
Closing this as obsolete. Please resubmit if it is still an issue with the rebuild.
