### ISSUE TITLE
amitool.h required

### ISSUE THREAD

**Issue by urherenow** [HiddenRamblings/Thenaya#17]
main.c wants amitool.h, which doesn't exist (even in the submodule). 

Things like "struct AmiiboIdStruct" and "AMIIBO_MAX_SIZE" are undefined 
(my uneducated guess is that those may exist in this amitool.h file)

**Comment by AbandonedCart** [comment]
It's been 6 years since this project was updated.

**Comment by urherenow** [comment]
I didn’t know it even needed updating. But now  new commits were merged, breaking the ability to build it without reverting said commits. Why would something be merged today, if it doesn’t result in the ability to build today, with today’s tools and libraries?

**Comment by AbandonedCart** [comment]
It needed updating for legal reasons.

The last commit before yesterday was August 3, 2017.

You are not being forced to sync the updates. I will post when it's done.

**Comment by AbandonedCart** [comment]
Done. It was brought to my attention Friday that this project was out of date and had some license issues. Unfortunately, I do have commitments outside of TagMo (and, by extension, Thenaya) that prevented spending the necessary time to fix and update it. As you can probably tell, it wasn't exactly a matter of simply deleting a folder and syncing it as a submodule, but the important part was no longer hosting amiitool and mbedtls without any link to their respective sources.
