### ISSUE TITLE
A  version of this that just dump everything

### ISSUE THREAD

**Issue by scj643** [HiddenRamblings/Thenaya#2]
Would it be possible to make a modification of this that just dumps NFC data and doesn't verify?

**Comment by HiddenRambler** [comment]
It already dumps the data even if the validation fails: 
https://github.com/HiddenRambler/Thenaya/blob/master/source/main.c#L196

^^ the validation failure only prints a warning. doesnt stop it.

**Comment by scj643** [comment]
Oh wait is the 3DS only able to read certain nfc types?

**Comment by HiddenRambler** [comment]
I believe so. but according to 3dbrew a not so well docuemented 2nd parameter of StartOtherTagScanning method changes the types. you could try different values to see if it helps with whatever type you are trying to scan. https://www.3dbrew.org/wiki/NFC:StartOtherTagScanning
