### ISSUE TITLE
Nintendo NFC Discord

### ISSUE THREAD

**Issue by scj643** [HiddenRamblings/Thenaya#4]
I made a discord channel that we can use for talk about Nintendo product's NFC capabilities and also get notifications for things on GitHub.

The invite link is https://discord.gg/z7nMt8d

**Comment by HiddenRambler** [comment]
@Bombastisch are you on discord?

**Comment by Bombastisch** [comment]
I have a account for like 1 minute now! xD   I'll join the channel now. Thank you for reminding me. :)
