### ISSUE TITLE
Red Screen of Death on app launch

### ISSUE THREAD

**Issue by ZacharyEggert** [HiddenRamblings/Thenaya#7]
Not sure if I have the wrong amiibo_keys.bin file or what but whenever I launch the app from homebrew it crashes to a RSOD

**Comment by urherenow** [comment]
As far as I can tell, everything is updated on my n3ds. Launching Thenaya v0.7 through HBL in Luma sysnand (b9s), it launches fine here.

/amiibo_keys.bin CRC32 is C6408C16

**Comment by nigel280** [comment]
I am also having this problem. I am unsure if it is due to the amiibo_keys.bin or a mishap on my part. Does it make a difference that I am using Freakyhax on a N3dsxl 11.8?
